VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GAX46QEMVKRQKREMHQXGDF2YLOTHVY76JKZPQPV2MVIQI43EKK7SHCCZ",
"GBMUGKI6P4QKNHX5GMKKWDD746WP3HUM5SPH5MSNZUW3VXDTA6S4ALDZ",
"GANJ2WWTQXBHN4ICQJEQZCOHQFGNFWUSONZ3ZLIJIEVRYJ57ELO4JDRY",
"GCM4UG6QYYNRFIM424WIQEAD5J6YQOKCWW4M7MPMT7IYRV5RQXDTJCGF"
]

[DOCUMENTATION]
ORG_NAME="qfssys"
ORG_DESCRIPTION="You are ready to become the next crypto millionaire"
ORG_DBA="qfssys.github.io"
ORG_URL="https://qfssys.github.io"
ORG_LOGO="https://qfssys.github.io/img/QXLM.png"
ORG_OFFICIAL_EMAIL="qfs.finance2024@gmail.com"

[[PRINCIPALS]]
name="qfssys"
email="qfs.finance2024@gmail.com"
github="qfssys"

[[CURRENCIES]]
code="QBTC"
status="live"
issuer="GAX46QEMVKRQKREMHQXGDF2YLOTHVY76JKZPQPV2MVIQI43EKK7SHCCZ"
display_decimals=7
name="QUANTBTC"
desc="Purchase each QBTC token from any holder for the value of 1 BITCOIN"
conditions="Withdrawal fees apply"
image="https://qfssys.github.io/img/QBTC.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="BTC"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yQBTC"
status="live"
issuer="GBMUGKI6P4QKNHX5GMKKWDD746WP3HUM5SPH5MSNZUW3VXDTA6S4ALDZ"
display_decimals=7
name="yieldQBTC"
desc="Purchase each yQBTC token from any holder for the value of 1 QBTC"
conditions="Withdrawal fees apply"
image="https://qfssys.github.io/img/yQBTC.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="QBTC"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="QXLM"
status="live"
issuer="GANJ2WWTQXBHN4ICQJEQZCOHQFGNFWUSONZ3ZLIJIEVRYJ57ELO4JDRY"
display_decimals=7
name="QXLM"
desc="Purchase each QXLM token from any holder for the value of 1 XLM"
conditions="Withdrawal fees apply"
image="https://qfssys.github.io/img/QXLM.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="QUSDC"
status="live"
issuer="GANJ2WWTQXBHN4ICQJEQZCOHQFGNFWUSONZ3ZLIJIEVRYJ57ELO4JDRY"
display_decimals=7
name="QUSDC"
desc="Purchase each QUSDC token from any holder for the value of 1 USDC"
conditions="Withdrawal fees apply"
image="https://qfssys.github.io/img/QUSDC.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="USDC"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="XVAULT"
status="live"
issuer="GCM4UG6QYYNRFIM424WIQEAD5J6YQOKCWW4M7MPMT7IYRV5RQXDTJCGF"
display_decimals=7
name="XVAULT"
desc="Purchase each XVAULT token from any holder for the value of 1 XLM"
conditions="Withdrawal fees apply"
image="https://qfssys.github.io/img/XVAULT.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="XLM"
anchor_asset_type="crypto"

